version: '4'
services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.0.1
    networks:
      - docker_net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    restart: always

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    networks:
      - docker_net
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: always

  cassandra:
    container_name: cassandra
    build: ./Cassandra/
    networks:
      - docker_net
    ports:
      - "9042:9042"
    volumes:
      - ./volume/cassandra:/var/lib/cassandra
    restart: always

  elasticsearch:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    networks:
      - docker_net
    ports:
      - 9200:9200
    volumes:
      - ./volume/elastic:/usr/share/elasticsearch/data
    restart: always

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.0.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    networks:
      - docker_net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    restart: always

  airflow:
    container_name: airflow
    build: ./Airflow/
    depends_on:
      - cassandra
      - kafka
      - elasticsearch
    networks:
      - docker_net
    ports:
      - 8080:8080
    volumes:
      - ../dags:/opt/airflow/dags
      - ../app:/opt/airflow/app
      - ../resources:/opt/resources
    restart: always

networks:
  docker_net:
